server:
  port: 5050

spring:
  #  mvc:
  #    static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true


  datasource:
    url: jdbc:mysql://localhost:3306/s201610309?useUnicode=true&characterEncoding=utf8
    username: s201610309
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true
      default_batch_fetch_size: 500
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
