server:
  port: 5051

file:
  dir: /home/yumin/Public/images/


spring:
  #  mvc:
  #    static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/ss201511162?useUnicode=true&characterEncoding=utf8
    username: root
    password: multi2021
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      show-sql: true
      default_batch_fetch_size: 500
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
